### ISSUE TITLE
[Mod Compatability] Tinkers Construct (probably others)

### ISSUE THREAD

**Issue by Dragnier** [MinecraftModDevelopment/OreSpawn#21] opened 2016-12-31 09:42 UTC
I tired turning off the default world gen for ores in Tinkers and adding them to orespawn, but it didn't work with either the release version or the latest alpha. I tried both adding them to the default orespawn.json and adding them to their own tconOrespawn.json file. Neither way worked. In the alpha version I even tried the /addore command and then editing the spawn parameters after.

Here is the way they were added by the /addore command other than my spawn parameter edits for size, variation, and frequency:
```
{
    "dimension": -1,
    "ores": [
      {
        "block": "tconstruct:ore",
	"state": "type=cobalt",
        "size": 3,
        "variation": 2,
        "frequency": 6,
        "min_height": 0,
        "max_height": 128
      },
	{
        "block": "tconstruct:ore",
	"state": "type=ardite",
        "size": 3,
        "variation": 2,
        "frequency": 6,
        "min_height": 0,
        "max_height": 128
      }
    ]
  }
```
The /give for these in a non-server environment are:

Cobalt = /give tconstruct:ore 1 0
Ardite = /give tconstruct:ore 1 1

This follows the vanilla /give where you specify the modid:itemname quantity metadata.

Sidenote: If you could allow specifying ores by ore dictionary entry in addition to specific blocks, that would be awesome and much easier in regards to most mod added ores.

**Comment by jriwanek** [comment] 2017-01-08 19:21
On by oredict entry, that would be relatively complex to code.

**Comment by dshadowwolf** [comment] 2017-06-23 15:52
This may be because of Tinkers loading after OreSpawn - as OreSpawn does all the work in the "Pre Init" phase of startup, it being loaded before Tinkers (or any other given mod) may be the cause of this. See issue #17 - this appears to be a duplicate of it, but I'll leave it open for now.

**Comment by dshadowwolf** [comment] 2017-08-24 19:21
This issue may have been resolved in the [latest code base](/MinecraftModDevelopmentMods/OreSpawn/tree/master-1.11.2) and there are testing-quality builds available on the [MMD Maven](https://maven.mcmoddev.com/com/mcmoddev/OreSpawn) and a slightly older release of the OreSpawn v3 code on CurseForge.

Can you test either the older v3 release or one of the more recent builds from the maven and let us know if the changes we've implemented have solved your issue ?

**Comment by dshadowwolf** [comment] 2017-10-11 19:42
Around the time of the OreSpawn 3.1 alphas this became a non-issue as we pushed off loading of configs until after all material registration and OreDictionary work had occurred. Closing this issue.

**Closed as completed by dshadowwolf** 2017-10-11 19:42 UTC
Labels: enhancement
