### ISSUE TITLE
Vein generator is still broken

### ISSUE THREAD

**Issue by CalaMariGold** [MinecraftModDevelopment/OreSpawn#172] opened 2020-03-28 23:13 UTC
> * Vein generator has been fixed to work properly

Veins are not generating in the size they are set to in the config. For some ore, I have a size of 3 and variation of 1, yet veins will be 10-15 blocks large.

This occurs for all ore. Nothing seems to be respecting the size and variation that I put.

**Comment by dshadowwolf** [comment] 2020-03-29 02:22
share the config in question - it might be that you're using parameter names that are valid for, say, "default" but incorrect for "vein"  (and yes, the parameters are named differently between different features)

**Comment by CalaMariGold** [comment] 2020-03-29 02:37
https://pastebin.com/5aJ0eHwt

**Comment by CalaMariGold** [comment] 2020-03-29 21:57
I found this on the wiki
```
				"minHeight": 16,
				"maxHeight": 80,
				"variation": 16,
				"frequency": 25,
				"minAttempts": 4,
				"maxAttempts": 8,
				"size": 4,
				"length": 32,
				"wander": 50
```

Can you explain what each one does? I can't find info about each on the wiki.

**Comment by dshadowwolf** [comment] 2020-03-30 02:16
Yeah - finally have time to reply and someone already has. "Size" in the vein generator is the size of an individual node - "length" is the length of the vein. "Wander" is how much it twists and turns... The Vein generator has different parameters to cover all the variability it offers. Closing as "not a bug, just a misunderstanding of parameters"

**Closed as completed by dshadowwolf** 2020-03-30 02:16 UTC

**Comment by CalaMariGold** [comment] 2020-03-30 23:54
What about the rest? minAttempts? variation? What do you mean "size of an individual node"? Is that how many ore blocks there are in a vein?

**Comment by dshadowwolf** [comment] 2020-03-31 00:05
A node is a single step along the vein - one "block" of the length that gets more added to it - "miAttempts" and "maxAttempts" describe an inclusive range for how many times to try and place a vein in a given chunk. Frequency is overall how often it should succeed, variation is difference in both length and size of node.

**Comment by CalaMariGold** [comment] 2020-03-31 00:40
> A node is a single step along the vein - one "block" of the length that gets more added to it 


What? Can you be anymore vague? I need to know exactly what all of this is so I don't have to spend 8 hours testing it. Can you give me an example? Like, what vanilla iron ore spawn is like, or at least similar to it.

**Comment by dshadowwolf** [comment] 2020-04-01 02:24
vein is generated by the system creating a "wandering line" of blocks through a chunk or chunks - each "step" of the process - ie: each block of the length - is a "node" where it will generate up to "size" blocks of the specified ore in a pattern around it. (And if my explanation still confuses, then realize this is why the documentation is barely there - I can write the code, but I can't explain it well)
