### ISSUE TITLE
Strange mod interaction with cofh core worldgen

### ISSUE THREAD

**Issue by Saereth** [MinecraftModDevelopment/OreSpawn#25] opened 2017-03-17 04:02 UTC
When using cofh core to control worldgen and running mmdorespawn along side it causes vanilla like generation in the end by cofh, dirt, gravel, coal etc  here is an image of it:
http://imgur.com/a/Fx8zi

This only seems to occur when I add orespawn (which is only added as a dependency for nethermetals and not to actually do any worldgen) 

Downgrading nether metals to a version not reliant on orespawn and removing orespawn clears this issue up. 

OreSpawn v2.0.0.15
CoFHCore-1.10.2-4.1.0.155-universal.jar

initially reported to cofh but doesn't seem to be on their end or perhaps some weird interaction going on here.
https://github.com/CoFH/Feedback/issues/92#issuecomment-287241429

**Comment by knoxhack** [comment] 2017-03-17 05:44
What version of OreSpawn are you using? Can you post the json file it generated? If OreSpawn 1.x under /config/orespawn, if OreSpawn 2.x under /orespawn

**Comment by Saereth** [comment] 2017-03-17 12:16
MMD Orespawn version 2.0.0.15
the file generated was called nethermetals-vanilla_ores.json
contents of that file are here: https://hastebin.com/zixoxilida.json

**Comment by knoxhack** [comment] 2017-03-17 12:28
I need to see the json file called orespawn.json

**Comment by Saereth** [comment] 2017-03-17 12:31
Here you go: https://hastebin.com/xeguweziqo.json

**Comment by knoxhack** [comment] 2017-03-17 12:38
Can you try deleting the orespawn.json file and let the mod create a new one and post it here.

**Comment by knoxhack** [comment] 2017-03-17 12:38
Also were you using any prior version of OreSpawn like the 1.x versions?

**Comment by Saereth** [comment] 2017-03-17 13:22
I never intentionally installed orespawn, curse automatically added it when I added nethermetals, so I dont believe so, but I can delete all the relevant jsons and recreate it later today when I'm home.

**Comment by dshadowwolf** [comment] 2017-06-23 15:57
This might be caused by OreSpawn 2's "retrogen" option being enabled (it is by default) - could you try disabling that ?

In OreSpawn 3 (which should be released by July 18, at the latest) this option defaults to "false" and retrogen does not run. However... as both OreSpawn and CoFH WorldGen register IWorldGenerator implementations there might still be an interaction.

@knoxhack BaseMetals and ModernMetals both have an option telling them that OreSpawn is not there and to not bother trying to use it - in cases where CoFH WorldGen is being used, having this option might be a good idea.

**Comment by dshadowwolf** [comment] 2017-08-26 21:14
The recent PR (#63) addressed an issue where the wrong config flag was in place to have OreSpawn replace vanilla ore generation. That might have also had an impact on and changed the situation here. Can you test this and confirm or deny the functionality, @Saereth ?

**Comment by dshadowwolf** [comment] 2018-01-08 05:55
The lack of any response from the original reporter and no ability to reproduce this bug leads me to believe it has been fixed in the OreSpawn 3 branch and is no longer valid. Closing.

**Closed as completed by dshadowwolf** 2018-01-08 05:55 UTC
