### ISSUE TITLE
WTF error

### ISSUE THREAD

**Issue by Sunconure11** [MinecraftModDevelopment/OreSpawn#146] opened 2018-11-30 22:33 UTC
https://pastebin.com/ENHHz0T8

**Comment by dshadowwolf** [comment] 2018-11-30 22:54
Known issue - there is a bug in certain versions that leads to this. Latest on CF should have the fix.

**Comment by Sunconure11** [comment] 2018-11-30 22:55
Strange, I am using the latest build on CF, and it happened anyways.

**Comment by Sunconure11** [comment] 2018-11-30 22:59
And it fired in the same way some old errors of mine had fired, when I used Nature's Compass to find a biome.

**Comment by dshadowwolf** [comment] 2019-03-04 15:51
yeah... the reported location of the error - "BlockList line 35" is a closing brace, and has been for a while - at the time this was reported 3.3.0 build 155 was the most recent (and should have fixed this, dammit!) but we have had several releases since then.

As I've been unable to reliably reproduce this, I'm looking for some confirmation that the bug is fixed. Can you test with 3.3.1 build 164 that was just released ?

**Comment by Sunconure11** [comment] 2019-03-05 05:18
I've not encountered this in a long while

**Comment by dshadowwolf** [comment] 2019-03-05 05:19
Closing as resolved

**Closed as completed by dshadowwolf** 2019-03-05 05:19 UTC
Labels: bug
