### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nickshark** [MinecraftModDevelopment/OreSpawn#159] opened 2019-05-25 05:11 UTC
Game crashed when i added base metals, modern metals, mmdorespawn and [mmdlibs.]
[crash-2019-05-24_22.57.20-client.txt](https://github.com/MinecraftModDevelopmentMods/OreSpawn/files/3219144/crash-2019-05-24_22.57.20-client.txt)

**Comment by dshadowwolf** [comment] 2019-05-25 05:26
-ERR_NOT_A_BUG

``java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.``

Your pack officially has more blocks than Minecraft 1.12 and prior can have without using a mod such as "Not Enough ID's" - not a bug in any MMD mod. Closing.

**Closed as completed by dshadowwolf** 2019-05-25 05:26 UTC
Labels: wrong-mod
